# Use a faster linker to speed up compilation
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
# For cross-compiling to Windows from Linux
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"